using GrowIT.Shared.DTOs;
using GrowIT.Infrastructure.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using GrowIT.Core.Interfaces;
using GrowIT.Core.Entities; 

using CoreProgram = GrowIT.Core.Entities.Program;

namespace GrowIT.API.Controllers;

[ApiController]
[Route("api/[controller]")]
public class FinancialsController : ControllerBase
{
    private readonly ApplicationDbContext _context;
    private readonly ICurrentTenantService _tenantService;

    public FinancialsController(ApplicationDbContext context, ICurrentTenantService tenantService)
    {
        _context = context;
        _tenantService = tenantService;
    }

    // ==========================================
    // FUNDS
    // ==========================================
    [HttpPost("funds")]
    public async Task<IActionResult> CreateFund(CreateFundRequest request)
    {
        var fund = new Fund
        {
            // ID is auto-generated by your Entity (Guid.NewGuid)
            Name = request.Name,
            TotalAmount = request.TotalAmount,
            AvailableAmount = request.TotalAmount, // Starts full
            TenantId = _tenantService.TenantId ?? Guid.Empty
        };

        _context.Funds.Add(fund);
        await _context.SaveChangesAsync();

        return Ok(new { Message = "Fund Created", FundId = fund.Id });
    }

[HttpGet("funds")]
    public async Task<ActionResult<List<FundDto>>> GetFunds()
    {
        var funds = await _context.Funds
            .Select(f => new FundDto 
            {
                Id = f.Id,
                Name = f.Name,
                TotalAmount = f.TotalAmount,
                AvailableAmount = f.AvailableAmount
            })
            .ToListAsync();

        return Ok(funds);
    }
    // ==========================================
    // PROGRAMS
    // ==========================================
    [HttpPost("programs")]
    public async Task<IActionResult> CreateProgram(CreateProgramRequest request)
    {
        // Use the alias 'CoreProgram' here to be safe
        var program = new CoreProgram
        {
            // ID is auto-generated by your Entity
            Name = request.Name,
            Description = request.Description ?? string.Empty, // Handle nulls safely
            DefaultUnitCost = request.DefaultUnitCost,
            TenantId = _tenantService.TenantId ?? Guid.Empty
        };

        _context.Programs.Add(program);
        await _context.SaveChangesAsync();

        return Ok(new { Message = "Program Created", ProgramId = program.Id });
    }

    [HttpGet("programs")]
    public async Task<IActionResult> GetPrograms()
    {
        return Ok(await _context.Programs.ToListAsync());
    }
}