using GrowIT.Shared.DTOs;
using GrowIT.Infrastructure.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using GrowIT.Core.Interfaces;
using GrowIT.Core.Entities; 

using CoreProgram = GrowIT.Core.Entities.Program;
using GrowIT.API.Services;
using GrowIT.API.Validators;

namespace GrowIT.API.Controllers;

[ApiController]
[Route("api/[controller]")]
public class FinancialsController : ControllerBase
{
    private readonly ApplicationDbContext _context;
    private readonly ICurrentTenantService _tenantService;
    private readonly ICurrentUserService _currentUserService;

    public FinancialsController(ApplicationDbContext context, ICurrentTenantService tenantService, ICurrentUserService currentUserService)
    {
        _context = context;
        _tenantService = tenantService;
        _currentUserService = currentUserService;
    }

    // ==========================================
    // FUNDS
    // ==========================================
    [HttpPost("funds")]
    public async Task<IActionResult> CreateFund(CreateFundRequest request)
    {
        var fund = new Fund
        {
            // ID is auto-generated by your Entity (Guid.NewGuid)
            Name = request.Name,
            TotalAmount = request.TotalAmount,
            AvailableAmount = request.TotalAmount, // Starts full
            TenantId = _tenantService.TenantId ?? Guid.Empty
        };

        _context.Funds.Add(fund);
        await _context.SaveChangesAsync();

        return Ok(new { Message = "Fund Created", FundId = fund.Id });
    }

[HttpGet("funds")]
    public async Task<ActionResult<List<FundDto>>> GetFunds()
    {
        var funds = await _context.Funds
            .Select(f => new FundDto 
            {
                Id = f.Id,
                Name = f.Name,
                TotalAmount = f.TotalAmount,
                AvailableAmount = f.AvailableAmount
            })
            .ToListAsync();

        return Ok(funds);
    }
    // ==========================================
    // PROGRAMS
    // ==========================================
    [HttpPost("programs")]
    public async Task<IActionResult> CreateProgram(CreateProgramRequest request)
    {
        // Use the alias 'CoreProgram' here to be safe
        var program = new CoreProgram
        {
            // ID is auto-generated by your Entity
            Name = request.Name,
            Description = request.Description ?? string.Empty, // Handle nulls safely
            DefaultUnitCost = request.DefaultUnitCost,
            TenantId = _tenantService.TenantId ?? Guid.Empty
        };

        _context.Programs.Add(program);
        await _context.SaveChangesAsync();

        return Ok(new { Message = "Program Created", ProgramId = program.Id });
    }

    [HttpGet("programs")]
    public async Task<IActionResult> GetPrograms()
    {
        return Ok(await _context.Programs.ToListAsync());
    }

    [HttpPut("funds/{id}")]
    public async Task<IActionResult> UpdateFund(Guid id, UpdateFundRequest request)
    {
        // 1. VALIDATION (The Enterprise Way)
        // We run the validator manually here to inject the 'id' and 'context'
        var validator = new UpdateFundRequestValidator(_context, id);
        var validationResult = await validator.ValidateAsync(request);

        if (!validationResult.IsValid)
            return BadRequest(validationResult.Errors.Select(e => e.ErrorMessage));

        var fund = await _context.Funds.FirstOrDefaultAsync(f => f.Id == id);
        if (fund == null) return NotFound("Fund not found.");

        // 2. PREPARE DATA (Capture old state for Audit)
        var oldName = fund.Name;
        var oldTotal = fund.TotalAmount;
        var oldAvailable = fund.AvailableAmount;

        // 3. APPLY UPDATE (Logic is now safe because Validator passed)
        var realUsage = await _context.Investments.Where(i => i.FundId == id).SumAsync(i => i.Amount);
        
        fund.Name = request.Name;
        fund.TotalAmount = request.TotalAmount;
        fund.AvailableAmount = request.TotalAmount - realUsage; 

        // 4. MANUAL AUDIT (Reason)
        var audit = new AuditLog
        {
            Id = Guid.NewGuid(),
            UserId = (Guid)_currentUserService.UserId,  
            TenantId = fund.TenantId,   
            ActionType = "Budget Adjustment",
            TableName = "Funds",
            RecordId = fund.Id,
            PreviousData = System.Text.Json.JsonSerializer.Serialize(new { Total = oldTotal, Available = oldAvailable, Name = oldName }),
            NewData = System.Text.Json.JsonSerializer.Serialize(new { Total = request.TotalAmount, Available = fund.AvailableAmount, Reason = request.ChangeReason }),
            CreatedAt = DateTime.UtcNow
        };

        _context.AuditLogs.Add(audit);
        await _context.SaveChangesAsync();

        return Ok(fund);
    }
}